In [3]:
"""
###    PERCEPTRON    ###
### RAMAZAN ÜSTÜNTAŞ ###
###     150401054    ### 

"""

import numpy as np

class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self,input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)  

In [ ]:
"""
--> 1.SORU "Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız."
 -> Cevap:

    1.fonksiyon *-* def __init__(self, input_size, lr=1, epochs=10) fonksiyonu: 

            "epochs" ve "lr" değişkenlerin değerleri varsayılan olarak parametrede atanmıştır.
        W parametresine sıfırlardan oluşan bir dizi tanımlanıyor. Algılayıcımızı oluşturmak için, ağırlık vektörümüzü oluşturmak için kaç girdi olduğunu bilmemiz gerekir.
        Ağırlık vektörüne sapmayı dahil etmek için input_size'a (+1) ekleniyor.
        
        Epochs=> Öğrenme algoritmasının tüm eğitim veri kümesinde kaç kez çalışacağını tanımlayan bir hiperparametredir. 
                *Pratik verilerinin kaç kez çalıştırılacağıdır*.
        
        Öğrenme Oranı/Hızı(LR)=> Öğrenme oranı/hızı(Learning Rate), model ağırlıkları her güncellendiğinde tahmin edilen hataya yanıt olarak modelin 
                          ne kadar değiştirileceğini kontrol eden bir hiperparametredir.  

    2.fonksiyon *-* def activation_fn(self, x) 
            
            Bu fonksiyon üretilen x değerinin kontrolünü gerçekleştiriyor. Üretilen X değeri sıfırdan büyükse 1, değilse 0 döndürmektedir. 
        Bu şekilde, Perceptron(Algılayıcı), iki sınıfı(0,1) ayırmak için doğrusal bir denklemin kullanılabileceği bir sınıflandırma olanağı sağlar.
    
    
    3.fonksiyon *-* def predict(self, x)
            
            Algılayıcı aracılığıyla bir girdi çalıştırmak ve bir çıktı döndürmek için bir işleve ihtiyacımız var. Geleneksel olarak buna "tahmin" denir.
        Eğilimi giriş vektörüne ekliyoruz. O zaman iç çarpımı basitçe hesaplayabilir ve aktivasyon fonksiyonunu uygulayabiliriz.
        Gelen x değerinin ilk değerine(index 0) 1'i eklemekte ve daha sonra bu değeri yukarıda oluşturduğu W'nin
        transpozesini alarak dot product işlemini gerçekleştirmekte ve bir çıktı elde edilmektedir. Bu işlemlerden çıkan z sonucunu
        def activation_fn fonksiyonuna parametre olarak gönderiliyor ve activation'dan gelen sonucu geri döndürüyor.
    
    
    4.fonksiyon *-* def fit(self, X, d)
            
            Girdiler ve istenen çıktılar verilen bir fonksiyon, perceptron öğrenme algoritmamızı çalıştırabiliriz. Ağırlıkları günceller.
        Ağırlık güncellemesini gerçekleştirirken input'a önyargı ekler.
        Ardından tahminimizi oluşturabilir, hatamızı hesaplayabilir ve güncelleme kuralımızı uygulayabiliriz.
            
            X'in içerisindeki veri kadar dolaşılmakta e = d - y formülü kullanarak hata(error) bulunmakta ve sonrasında
         w = w + n . e . x formülü uygulanmaktadır.


"""

In [4]:
"""
-->2.SORU "XOR için verileri değiştirip çalışmasınızı gözlemleyiniz."

 ->Cevap: """

d_XOR = np.array([0, 1, 1, 0]) # XOR [0,1,1,0]

perceptron_XOR = Perceptron(input_size=2)
perceptron_XOR.W

array([0., 0., 0.])

In [18]:
# XOR SONUCUNDA [ 0. -1.  0.] ELDE EDİLİYOR.
perceptron_XOR.fit(X, d_XOR)
print(perceptron_XOR.W)      

[ 0. -1.  0.]


In [ ]:
"""
-->3.SORU "bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız."
 ->Cevap:
    
        40 imzanın herbiri için bir yükseklik-genişlik inputu olur. X, 100x100 lük bir imza image'ında (100*100*3,40) matris verisi olacaktır.
    d'ye karşılık 40 farklı çıktı değeri olacaktır. Predict fonksiyonunda ise 40 kişilik bir sınıfın imza stoğu için herbir imzanın tahmini elde 
    edilir, activation_fn fonksiyonuna gönderilir ve fit için bir geri döndürüm sağlanır.

"""

In [ ]:
"""
--> 4.SORU "Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız."
 -> Cevap:
            Ölçüm aracı olarak elimizde tahmin edilen(olası) bir çıktı ile asıl gerçek sonucun farkından yararlanılarak hata bulunabilir.
            Tahmini sonuç ile asıl sonucun farkı yardımıyla asıl(istenen) sonucun tahmini sonuçtan sapma payı ölçülebilir ve bu pay "hata" olarak 
            kabul edilebilir/tanımlanabilir.
"""

In [6]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [7]:
d = np.array([0, 0, 0, 1])

In [8]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [9]:
d

array([0, 0, 0, 1])

In [10]:
perceptron = Perceptron(input_size=2)

In [11]:
perceptron.W

array([0., 0., 0.])

In [12]:
perceptron.fit(X, d)

In [13]:
print(perceptron.W)

[-3.  2.  1.]


In [14]:
perceptron.predict(np.asarray([1,1]))

1

In [15]:
mp=Perceptron(5)
x=np.asarray([-10,2,-30,4,-50])  ##  ndarray dim different
mp.predict(x)

1

In [16]:
mp.activation_fn(-10)

0

In [17]:
np.insert(mp.W,0,100)

array([100.,   0.,   0.,   0.,   0.,   0.,   0.])